# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '03.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(903, 509)
        Dialog.setStyleSheet("background-color: black;")
        self.str1 = QtWidgets.QTextEdit(Dialog)
        self.str1.setGeometry(QtCore.QRect(20, 70, 411, 311))
        self.str1.setStyleSheet("background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 5px;")
        self.str1.setObjectName("str1")
        self.str2 = QtWidgets.QTextEdit(Dialog)
        self.str2.setGeometry(QtCore.QRect(460, 70, 421, 311))
        self.str2.setStyleSheet("background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 5px;")
        self.str2.setObjectName("str2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(390, 10, 111, 21))
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.btn = QtWidgets.QPushButton(Dialog)
        self.btn.setGeometry(QtCore.QRect(410, 400, 75, 23))
        self.btn.setStyleSheet("QPushButton {\n"
"background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(100,100,100);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: rgb(50,50,50);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:disabled {\n"
"   background-color: rgb(70,70,70);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.btn.setObjectName("btn")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 40, 201, 21))
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.Porog = QtWidgets.QSpinBox(Dialog)
        self.Porog.setGeometry(QtCore.QRect(180, 40, 701, 22))
        self.Porog.setStyleSheet("background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 5px;")
        self.Porog.setPrefix("")
        self.Porog.setMaximum(100)
        self.Porog.setObjectName("Porog")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 450, 881, 41))
        self.label_3.setStyleSheet("color: white;\n"
"border-radius: 5px;\n"
"")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Антиплагиатор 3000"))
        self.btn.setText(_translate("Dialog", "Сверить"))
        self.label_2.setText(_translate("Dialog", "Укажи порог ругательства"))
