# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '01.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Authorization(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(404, 311)
        Dialog.setStyleSheet("background-color: black;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 20, 71, 21))
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.log_in = QtWidgets.QPushButton(Dialog)
        self.log_in.setGeometry(QtCore.QRect(110, 240, 75, 23))
        self.log_in.setStyleSheet("QPushButton {\n"
"background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(100,100,100);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: rgb(50,50,50);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:disabled {\n"
"   background-color: rgb(70,70,70);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.log_in.setObjectName("log_in")
        self.reg = QtWidgets.QPushButton(Dialog)
        self.reg.setGeometry(QtCore.QRect(210, 240, 81, 23))
        self.reg.setStyleSheet("QPushButton {\n"
"background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(100,100,100);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: rgb(50,50,50);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:disabled {\n"
"   background-color: rgb(70,70,70);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.reg.setObjectName("reg")
        self.login = QtWidgets.QLineEdit(Dialog)
        self.login.setGeometry(QtCore.QRect(40, 120, 321, 20))
        self.login.setStyleSheet("background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 5px;")
        self.login.setObjectName("login")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 160, 321, 20))
        self.lineEdit_2.setStyleSheet("background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 5px;")
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Авторизация"))
        self.log_in.setText(_translate("Dialog", "Вход"))
        self.reg.setText(_translate("Dialog", "Регистрация"))
        self.login.setText(_translate("Dialog", "Логин"))
        self.lineEdit_2.setText(_translate("Dialog", "Пароль"))
