# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '02.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Registration(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(393, 359)
        Dialog.setStyleSheet("background-color: black;\n"
"")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 20, 71, 20))
        self.label.setStyleSheet("color: white;\n"
"")
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(Dialog)
        self.spinBox.setGeometry(QtCore.QRect(120, 210, 42, 22))
        self.spinBox.setStyleSheet("background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 5px;")
        self.spinBox.setObjectName("spinBox")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 210, 71, 20))
        self.label_2.setStyleSheet("color: white;\n"
"")
        self.label_2.setObjectName("label_2")
        self.reg_2 = QtWidgets.QPushButton(Dialog)
        self.reg_2.setGeometry(QtCore.QRect(130, 290, 121, 23))
        self.reg_2.setStyleSheet("QPushButton {\n"
"background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(100,100,100);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: rgb(50,50,50);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"QPushButton:disabled {\n"
"   background-color: rgb(70,70,70);\n"
"color: white;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"")
        self.reg_2.setObjectName("reg_2")
        self.error_txt = QtWidgets.QLabel(Dialog)
        self.error_txt.setGeometry(QtCore.QRect(10, 321, 371, 20))
        self.error_txt.setStyleSheet("color: white;\n"
"")
        self.error_txt.setText("")
        self.error_txt.setObjectName("error_txt")
        self.man = QtWidgets.QRadioButton(Dialog)
        self.man.setGeometry(QtCore.QRect(140, 250, 82, 17))
        self.man.setStyleSheet("color: white;")
        self.man.setObjectName("man")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 250, 71, 20))
        self.label_4.setStyleSheet("color: white;\n"
"")
        self.label_4.setObjectName("label_4")
        self.woman = QtWidgets.QRadioButton(Dialog)
        self.woman.setGeometry(QtCore.QRect(220, 250, 82, 17))
        self.woman.setStyleSheet("color: white;")
        self.woman.setObjectName("woman")
        self.login = QtWidgets.QLineEdit(Dialog)
        self.login.setGeometry(QtCore.QRect(40, 130, 321, 20))
        self.login.setStyleSheet("background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 5px;")
        self.login.setObjectName("login")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(40, 170, 321, 20))
        self.password.setStyleSheet("background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 5px;")
        self.password.setObjectName("password")
        self.Email = QtWidgets.QLineEdit(Dialog)
        self.Email.setGeometry(QtCore.QRect(40, 50, 321, 20))
        self.Email.setStyleSheet("background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 5px;")
        self.Email.setObjectName("Email")
        self.name = QtWidgets.QLineEdit(Dialog)
        self.name.setGeometry(QtCore.QRect(40, 90, 151, 20))
        self.name.setStyleSheet("background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 5px;")
        self.name.setObjectName("name")
        self.surname = QtWidgets.QLineEdit(Dialog)
        self.surname.setGeometry(QtCore.QRect(200, 90, 151, 20))
        self.surname.setStyleSheet("background-color: rgb(36,36,36);\n"
"color: white;\n"
"border-radius: 5px;")
        self.surname.setObjectName("surname")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Регистрация "))
        self.label_2.setText(_translate("Dialog", "Ваш возраст:"))
        self.reg_2.setText(_translate("Dialog", "Зарегистрироваться"))
        self.man.setText(_translate("Dialog", "Мужской"))
        self.label_4.setText(_translate("Dialog", "Ваш пол:"))
        self.woman.setText(_translate("Dialog", "Женский"))
        self.login.setText(_translate("Dialog", "Логин"))
        self.password.setText(_translate("Dialog", "Пароль"))
        self.Email.setText(_translate("Dialog", "Email"))
        self.name.setText(_translate("Dialog", "Имя"))
        self.surname.setText(_translate("Dialog", "Фамилия"))
